// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

exodus.wad
gfx/env/mars2bk.tga
gfx/env/mars2dn.tga
gfx/env/mars2ft.tga
gfx/env/mars2lf.tga
gfx/env/mars2rt.tga
gfx/env/mars2up.tga
models/altoverride/p_crowbar.mdl
models/altoverride/w_crowbar.mdl
models/rngstuff/kuilu/k_crate.mdl
models/rngstuff/morass_beta/de_roach.mdl
models/scmod/alab/svensci.mdl
models/scmod/exodus/fungus(large).mdl
models/scmod/exodus/fungus.mdl
models/scmod/exodus/molepeople_gun.mdl
models/scmod/exodus/morass_prototree.mdl
models/scmod/exodus/robocontroller.mdl
models/scmod/jed/tfc_demo_hgrunt.mdl
models/scmod/jed/tfc_engineer.mdl
models/scmod/jed/tfc_hgrunt.mdl
models/scmod/jed/tfc_hwgrunt.mdl
models/scmod/jed/tfc_massn.mdl
models/scmod/jed/tfc_medic.mdl
models/scmod/jed/tfc_opforgrunt.mdl
models/scmod/jed/tfc_otis.mdl
models/scmod/jed/tfc_pyro.mdl
models/scmod/jed/tfc_scout_hgrunt.mdl
models/scmod/jed/tfc_sentry.mdl
models/scmod/jed/tfc_soldier_hgrunt.mdl
models/scmod/npcs/barnotis/nev.mdl
models/scmod/npcs/barnotis/policelt.mdl
models/scmod/npcs/barnotis/sphinx.mdl
models/scmod/npcs/hgrunt/tylak.mdl
models/scmod/npcs/massn/lento.mdl
models/scmod/npcs/scientist/codeman.mdl
models/scmod/npcs/scientist/thebutterman.mdl
models/scmod/npcs/strooper/viger.mdl
models/scmod/weapons/mars/garand/p_desert_eagle.mdl
models/scmod/weapons/mars/garand/v_desert_eagle.mdl
models/scmod/weapons/mars/garand/w_desert_eagle.mdl
models/scmod/weapons/mars/hammer/p_hammer.mdl
models/scmod/weapons/mars/hammer/v_hammer.mdl
models/scmod/weapons/mars/hammer/w_hammer.mdl
models/scmod/zubben/barnspace.mdl
models/scmod/zubben/hgruntf.mdl
models/scmod/zubben/molepeople.mdl
models/xad/stukabat_fast.mdl
models/xad/v_crowbar.mdl
models/xad_zubben/p_9mmar.mdl
models/xad_zubben/p_shotgun.mdl
models/xad_zubben/v_9mmar.mdl
models/xad_zubben/v_shotgun.mdl
models/xad_zubben/w_9mmar.mdl
models/xad_zubben/w_shotgun.mdl
sound/scmod/exodus/dialogs/1codeman.ogg
sound/scmod/exodus/dialogs/2butterman.ogg
sound/scmod/exodus/dialogs/3codeman.ogg
sound/scmod/exodus/dialogs/4jpolito_s.ogg
sound/scmod/exodus/dialogs/5grunt.ogg
sound/scmod/exodus/dialogs/6tylak.ogg
sound/scmod/exodus/dialogs/7viger.ogg
sound/scmod/exodus/dialogs/c3a2_sci_straws_fixed.ogg
sound/scmod/exodus/dialogs/sciradio.ogg
sound/scmod/exodus/hevbeat.ogg
sound/scmod/exodus/klaxon_vandoorea.ogg
sound/scmod/npcs/barniel/aimforhead.wav
sound/scmod/npcs/barniel/badfeeling.wav
sound/scmod/npcs/barniel/bequiet.wav
sound/scmod/npcs/barniel/bn_another.wav
sound/scmod/npcs/barniel/bn_attack1.wav
sound/scmod/npcs/barniel/bn_becarefull.wav
sound/scmod/npcs/barniel/bn_bring.wav
sound/scmod/npcs/barniel/bn_carefull.wav
sound/scmod/npcs/barniel/bn_close.wav
sound/scmod/npcs/barniel/bn_die1.wav
sound/scmod/npcs/barniel/bn_dontdothat.wav
sound/scmod/npcs/barniel/bn_dontmake.wav
sound/scmod/npcs/barniel/bn_endline.wav
sound/scmod/npcs/barniel/bn_firepl.wav
sound/scmod/npcs/barniel/bn_friends.wav
sound/scmod/npcs/barniel/bn_gotone.wav
sound/scmod/npcs/barniel/bn_onelessh.wav
sound/scmod/npcs/barniel/bn_pain1.wav
sound/scmod/npcs/barniel/bn_pain2.wav
sound/scmod/npcs/barniel/bn_seethat.wav
sound/scmod/npcs/barniel/bn_stepoff.wav
sound/scmod/npcs/barniel/bn_tomb.wav
sound/scmod/npcs/barniel/bn_whatyou.wav
sound/scmod/npcs/barniel/diegreenthing.wav
sound/scmod/npcs/barniel/dontagree.wav
sound/scmod/npcs/barniel/dontknow.wav
sound/scmod/npcs/barniel/drinktopside.wav
sound/scmod/npcs/barniel/hearsomething.wav
sound/scmod/npcs/barniel/hevno.wav
sound/scmod/npcs/barniel/hi.wav
sound/scmod/npcs/barniel/hitbad.wav
sound/scmod/npcs/barniel/hoyes.wav
sound/scmod/npcs/barniel/humm.wav
sound/scmod/npcs/barniel/imhit.wav
sound/scmod/npcs/barniel/movietv.wav
sound/scmod/npcs/barniel/nosir.wav
sound/scmod/npcs/barniel/notatall.wav
sound/scmod/npcs/barniel/openfire.wav
sound/scmod/npcs/barniel/rightway.wav
sound/scmod/npcs/barniel/seelater.wav
sound/scmod/npcs/barniel/seeya.wav
sound/scmod/npcs/barniel/seeyoulater.wav
sound/scmod/npcs/barniel/somethingmoves.wav
sound/scmod/npcs/barniel/teamup1.wav
sound/scmod/npcs/barniel/teamup2.wav
sound/scmod/npcs/barniel/thinking.wav
sound/scmod/npcs/barniel/whatsgoingon.wav
sound/scmod/npcs/barniel/yesbarn.wav
sound/scmod/npcs/barniel/yessir.wav
sound/scmod/npcs/barniel/youneedmedic.wav
sound/scmod/npcs/molepeople/alert.ogg
sound/scmod/npcs/molepeople/alert2.ogg
sound/scmod/npcs/molepeople/idle1.ogg
sound/scmod/npcs/molepeople/idle2.ogg
sound/scmod/npcs/molepeople/idle3.ogg
sound/scmod/npcs/molepeople/menkey.ogg
sound/scmod/npcs/molepeople/menkey2.ogg
sound/weapons/c96g/BoltBack.wav
sound/weapons/c96g/BoltClose.wav
sound/weapons/c96g/magin.ogg
sound/weapons/c96g/ping1.ogg
sound/weapons/c96g/ping4.ogg
sound/weapons/cock.wav
sound/xad/oldcocking1.wav
sound/xad/oldcocking2.wav
