// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/fi/5ton.mdl
models/fi/eye_scanner.mdl
models/fi/floater.mdl
models/fi/gamma.mdl
models/fi/gus.mdl
models/fi/hgrunt_fi.mdl
models/fi/houndeye_dead.mdl
models/fi/item_valve.mdl
models/fi/props/ac_large.mdl
models/fi/props/dolly.mdl
models/fi/props/forklift.mdl
models/fi/props/machinery_static.mdl
models/fi/sentry.mdl
models/fi/truck.mdl
models/fi/v_displacer.mdl
models/fi/worker.mdl
models/fi/zombie.mdl
models/fi/zombie_barney.mdl
models/fi/zombie_soldier.mdl
sound/decay/colette/colette_attack2.wav
sound/decay/gina/gina_attack2.wav
sound/fi/ambience/damage_boom_loop.wav
sound/fi/ambience/damage_guns_loop.wav
sound/fi/ambience/portal_voices.wav
sound/fi/barney/ba_dooraccess.wav
sound/fi/barney/ba_gamma.wav
sound/fi/barney/ba_scanner.wav
sound/fi/barney/ba_whyyouhere.wav
sound/fi/barney/ba_youneedme.wav
sound/fi/fgrunt/fg_headevac.wav
sound/fi/fgrunt/fg_ladies.wav
sound/fi/fgrunt/fg_novfreeman.wav
sound/fi/fgrunt/fg_novhello.wav
sound/fi/fgrunt/fg_novnowaya.wav
sound/fi/fgrunt/fg_novnowayb.wav
sound/fi/fgrunt/fg_shephard1.wav
sound/fi/fgrunt/fg_shephard2.wav
sound/fi/fgrunt/fg_shephard3.wav
sound/fi/fgrunt/tg_broken.wav
sound/fi/fgrunt/tg_dogs.wav
sound/fi/fgrunt/tg_eleva.wav
sound/fi/fgrunt/tg_elevb.wav
sound/fi/fgrunt/tg_gates.wav
sound/fi/fgrunt/tg_nvg.wav
sound/fi/fgrunt/tg_panel.wav
sound/fi/fgrunt/tg_power.wav
sound/fi/fgrunt/tg_stuck.wav
sound/fi/fgrunt/tg_zombies.wav
sound/fi/floater/floater_howl.wav
sound/fi/floater/floater_pain1.wav
sound/fi/floater/floater_pain2.wav
sound/fi/floater/floater_pain3.wav
sound/fi/floater/floater_spinup.wav
sound/fi/greg/gg_blowgates.wav
sound/fi/greg/gg_cantbelieve.wav
sound/fi/greg/gg_keepseye.wav
sound/fi/greg/gg_ohcrap.wav
sound/fi/hl2/eli_kleinerstop.wav
sound/fi/hl2/eli_whatgoingon.wav
sound/fi/hl2/kl_greatscott.wav
sound/fi/keller/dk_newstuff.wav
sound/fi/kevin/kv_accompany.wav
sound/fi/kevin/kv_antiair.wav
sound/fi/kevin/kv_barney.wav
sound/fi/kevin/kv_blackops.wav
sound/fi/kevin/kv_brief.wav
sound/fi/kevin/kv_catchup.wav
sound/fi/kevin/kv_checkhev.wav
sound/fi/kevin/kv_connect.wav
sound/fi/kevin/kv_contact.wav
sound/fi/kevin/kv_darkness.wav
sound/fi/kevin/kv_death.wav
sound/fi/kevin/kv_doorway.wav
sound/fi/kevin/kv_eleva.wav
sound/fi/kevin/kv_elevb.wav
sound/fi/kevin/kv_evac.wav
sound/fi/kevin/kv_examinehev.wav
sound/fi/kevin/kv_freeman.wav
sound/fi/kevin/kv_hearme.wav
sound/fi/kevin/kv_hello.wav
sound/fi/kevin/kv_hereiam.wav
sound/fi/kevin/kv_hevsuit.wav
sound/fi/kevin/kv_hevtrack.wav
sound/fi/kevin/kv_keys.wav
sound/fi/kevin/kv_limaisnear.wav
sound/fi/kevin/kv_lucky.wav
sound/fi/kevin/kv_mantarays.wav
sound/fi/kevin/kv_newobj.wav
sound/fi/kevin/kv_novattacked.wav
sound/fi/kevin/kv_november.wav
sound/fi/kevin/kv_objectives.wav
sound/fi/kevin/kv_onthetrack.wav
sound/fi/kevin/kv_order.wav
sound/fi/kevin/kv_othersci.wav
sound/fi/kevin/kv_radio.wav
sound/fi/kevin/kv_responda.wav
sound/fi/kevin/kv_respondb.wav
sound/fi/kevin/kv_restcrew.wav
sound/fi/kevin/kv_return.wav
sound/fi/kevin/kv_reunite.wav
sound/fi/kevin/kv_rocket.wav
sound/fi/kevin/kv_rosenberg.wav
sound/fi/kevin/kv_satellite.wav
sound/fi/kevin/kv_sectore.wav
sound/fi/kevin/kv_setuptrap.wav
sound/fi/kevin/kv_sierra.wav
sound/fi/kevin/kv_squadalpha.wav
sound/fi/kevin/kv_theymad.wav
sound/fi/kevin/kv_whatisthis.wav
sound/fi/materials.txt
sound/fi/panthereye/pa_idle1.wav
sound/fi/panthereye/pa_idle2.wav
sound/fi/panthereye/pa_idle3.wav
sound/fi/panthereye/pa_idle4.wav
sound/fi/scientist/sc_biobye.wav
sound/fi/scientist/sc_biogamma.wav
sound/fi/scientist/sc_biogarg.wav
sound/fi/scientist/sc_biohello.wav
sound/fi/scientist/sc_bioletsgo.wav
sound/fi/scientist/sc_bioplan.wav
sound/fi/scientist/sc_biotest.wav
sound/fi/scientist/sc_biounlock.wav
sound/fi/scientist/sc_bothwork.wav
sound/fi/scientist/sc_commonenemy.wav
sound/fi/scientist/sc_dangerfire.wav
sound/fi/scientist/sc_dangergas.wav
sound/fi/scientist/sc_dangerrad.wav
sound/fi/scientist/sc_detour.wav
sound/fi/scientist/sc_device.wav
sound/fi/scientist/sc_displacer.wav
sound/fi/scientist/sc_getround.wav
sound/fi/scientist/sc_goodluck.wav
sound/fi/scientist/sc_keepgoing.wav
sound/fi/scientist/sc_lockedgates.wav
sound/fi/scientist/sc_medkit.wav
sound/fi/scientist/sc_military.wav
sound/fi/scientist/sc_noweapons.wav
sound/fi/scientist/sc_satellite.wav
sound/fi/scientist/sc_situation.wav
sound/fi/scientist/sc_woken.wav
sound/fi/scientist/sc_worry.wav
sound/fi/wheelchair/wheelchair_jog.wav
sound/fi/wheelchair/wheelchair_run.wav
sound/fi/wheelchair/wheelchair_walk.wav
sound/fi/worker/wr_leavealone.wav
sound/fi/worker/wr_surface.wav
sound/fi/worker/wr_swarmed.wav
sprites/fi/640hud7.spr
sprites/fi/640hudof03.spr
sprites/fi/640hudof04.spr
sprites/fi/weapon_knife.spr
sprites/fi/weapon_knife.txt
sprites/fi/weapon_penguin.txt
